name: build-and-package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version: ex. 2.0.0'
        required: true
  release:
    types:
      - created

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Cache Maven wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            .mvn/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get deploy version or dispatch input
        id: resolve-tag
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          if [ -z "$VERSION" ]; then
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "Resolved version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set project version in POM
        run: ./mvnw versions:set -DnewVersion=${{ steps.resolve-tag.outputs.version }}

      - name: Build and deploy to GitHub Packages
        run: ./mvnw clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
