name: generate-release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  discussions: write

jobs:
  create-release:
    if: |
      github.event.pull_request.merged == true &&
      (
        contains(github.event.pull_request.labels.*.name, 'release-type/major') ||
        contains(github.event.pull_request.labels.*.name, 'release-type/minor') ||
        contains(github.event.pull_request.labels.*.name, 'release-type/patch')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine release type
        id: release_type
        uses: matiasmartin-labs/gha-deployments/determine-release-type@main

      - name: Calculate next version
        id: calculate_version
        uses: matiasmartin-labs/gha-deployments/determine-next-version@main
        with:
          release-type: ${{ steps.release_type.outputs.type }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.calculate_version.outputs.new-version }}
          name: Release ${{ steps.calculate_version.outputs.new-version-tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GH_TOKEN }} # it is necessary for execute other workflows, https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#about-the-github_token-secret
